#!/bin/bash

SRC_PYTHON_DIR=/home/pi/Projects/P2-BLDC-Control
DST_PYTHON_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects P2/P2-BLDC-Motor-Control/P2-BLDC-Motor-Control/pythonSrc"

SRC_SPIN_DIR=/Users/stephen/Dropbox/PropV2-Shared/Projects/P2-BLDC-Motor-ControlSW
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Propeller2/P2-BLDC-MotorControl/P2-BLDC-Motor-Control/src"

DST_SPIN_DIR2="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects P2/P2-BLDC-Motor-Control/P2-BLDC-Motor-Control/src"

if [ ! -d "${DST_SPIN_DIR}" ]; then
    DST_SPIN_DIR="${DST_SPIN_DIR2}"
fi

#(set -x;sdiff -s "${SRC_SPIN_DIR}"/*.spin2 "${DST_SPIN_DIR}")
#(set -x;cp -p "${SRC_SPIN_DIR}"/p2font16 "${DST_SPIN_DIR}")
#(set -x;scp -p pi@pip2iotgw-wifi.home:"${SRC_PYTHON_DIR}"/* "${DST_PYTHON_DIR}")


for SPINFIL in "${SRC_SPIN_DIR}"/*.spin2; do
    SPINBASE=$(basename "${SPINFIL}")
    echo ""
    echo "-- ${SPINBASE}"
    (sdiff -s "${SRC_SPIN_DIR}/${SPINBASE}" "${DST_SPIN_DIR}/${SPINBASE}")
done
