#!/bin/bash

SRC_SPIN_DIR=/Users/stephen/Dropbox/PropV2-Shared/Projects/P2-BLDC-Motor-ControlSW
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects Propeller/P2-BLDC-Motor-Control/P2-BLDC-Motor-Control/src"
DST_SPIN_DIR2="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Propeller2/P2-BLDC-MotorControl/P2-BLDC-Motor-Control/src"

if [ ! -d "${DST_SPIN_DIR}" ]; then
  DST_SPIN_DIR="${DST_SPIN_DIR2}"
fi

(set -x;cp -p "${SRC_SPIN_DIR}"/*.spin2 "${DST_SPIN_DIR}")
(set -x;cp -p "${SRC_SPIN_DIR}"/p2font16 "${DST_SPIN_DIR}")
