#!/bin/bash

DBXPATH=/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/Projects/P2-BLDC-Motor-ControlSW

# Check for file-changes in Dropbox vs. git repo

OUTFILE=./chk.diff
echo "" > $OUTFILE   # empty prior output

for FILSPEC in $DBXPATH/*.spin2; do
    #echo $FIL
    # Skip files with "RLS" in their name
    if [[ $FILSPEC == *RLS* || $FILSPEC == *MINE* ]]; then
        continue
    fi

    FIL=`basename $FILSPEC`
    LEFT=`md5 $FIL`
    cd $DBXPATH 2>/dev/null 1>&2
    RIGHT=`md5 $FIL`
    cd - 2>/dev/null 1>&2

    if [ "$LEFT" != "$RIGHT" ]; then
        echo "Diff: diff $FIL"
        #echo "Diff: diff $DBXPATH/$FIL $FIL"
        echo "" >> $OUTFILE
        echo "diff $DBXPATH/$FIL $FIL" >> $OUTFILE
        diff $DBXPATH/$FIL $FIL >> $OUTFILE 2>&1
    fi

done
echo "Done: Diffs logged to $OUTFILE"
