#!/bin/bash

DBXPATH=/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/Projects/P2-BLDC-Motor-ControlSW

# Check for file-changes in Dropbox vs. git repo

for FILSPEC in $DBXPATH/*.spin2; do
    #echo $FIL
    # Skip files with "RLS" in their name
    if [[ $FILSPEC == *RLS* || $FILSPEC == *MINE* ]]; then
        continue
    fi

    FIL=`basename $FILSPEC`
    LEFT=`md5 $FIL`
    cd $DBXPATH 2>/dev/null 1>&2
    RIGHT=`md5 $FIL`
    cd - 2>/dev/null 1>&2

    if [ "$LEFT" != "$RIGHT" ]; then
        #echo "cp -p $DBXPATH/$FIL $FIL"
        (set -x; cp -p $DBXPATH/$FIL $FIL)
    fi

done
echo "Done"
